CLUSTERING = "clustering.pi"
EXPRESSION = "exp.pi"
XYS = "xys.pi"
MARKER_TABLE = "markers.pi"
CELL_TYPE_ANNOTATION = "celltype_annotate.pi"
STATE = "state.json.gz"
SPLIT_CLUSTER_DICT = "cluster_dict.pi"
DOTPLOT_SIZE_COLOR_METRICS = "size-color.pi"
all_filenames = [CLUSTERING, EXPRESSION, XYS, MARKER_TABLE, STATE, CELL_TYPE_ANNOTATION, DOTPLOT_SIZE_COLOR_METRICS]